---
apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: immich-photos-snapshot
  namespace: home-services
spec:
  snapshotClassName: truenas-nfs
  persistentVolumeClaimName: immich-photos
  snapshotFrequency: 1d
  snapshotRetention: 30d
---
apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: immich-postgres-snapshot
  namespace: home-services
spec:
  snapshotClassName: truenas-iscsi
  persistentVolumeClaimName: immich-postgresql-1
  snapshotFrequency: 1d
  snapshotRetention: 30d
