---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-external
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/michaeljwood/home-lab.git
      path: kubernetes/apps/traefik/common
      targetRevision: main
      ref: repo
    - repoURL: https://github.com/michaeljwood/home-lab.git
      path: kubernetes/apps/traefik/tls
      targetRevision: main
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 39.0.1
      helm:
        releaseName: traefik-external
        valueFiles:
          - $repo/kubernetes/apps/traefik/external/values.yaml
  destination:
    name: in-cluster
    namespace: traefik
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
