#---
#apiVersion: k8s.ryanorth.io/v1beta1
#kind: ScheduledVolumeSnapshot
#metadata:
#  name: jellyfin-config-snapshot
#  namespace: home-services
#spec:
#  snapshotClassName: truenas-iscsi
#  persistentVolumeClaimName: jellyfin-config
#  snapshotFrequency: 1d
#  snapshotRetention: 30d
