apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgresql
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  instances: 1

  managed:
    roles:
      - name: gitea
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      secret:
        name: gitea-postgresql-user

  storage:
    size: 10Gi
    storageClass: nas-iscsi
