---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nas-flash-iscsi
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/democratic-csi/nas-flash-iscsi
      targetRevision: main
      ref: repo
    - repoURL: "https://democratic-csi.github.io/charts/"
      chart: democratic-csi
      targetRevision: 0.15.1
      helm:
        releaseName: nas-flash-iscsi
        valueFiles:
          - $repo/kubernetes/apps/democratic-csi/nas-flash-iscsi/values.sops.yaml
  destination:
    name: in-cluster
    namespace: democratic-csi
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
