apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
data:
  config.yaml: ENC[AES256_GCM,data:GlowKG1OBbLC8kmlUCRdrzU5saIh7pxOxkoCut4efpldf4YoUg6rC1EIJn7OKYoTsN4iSLL9FTWg04PszQqlOP0czn5xQwyNGgEr6fMW0AYibR4DdLJS0gafBtAJfzXw3u9lYTZ76DdNyXuwu8zx7GF2OfnPS9N84APtBpykQMHj8BZtnCkNEwr9uqLI25FbIgYAIzDW3pmv44QEaggntVwQ94+KXQdP7DFbT8OFZXuYIEOw5FefkWfxUNKlCSAbWj4M3dMDobr07o1bC5AN1hvxOgfOk05aRkxau6eRQ64w34vMILSmK90qJUHezaxrVZOITdK4vw==,iv:BpYRg6uRAOusiX3NzBqflfWyfm0OXu2ZdimoUL8c7R0=,tag:JKBmXHOSqIjJtvbv/Popdw==,type:str]
sops:
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWHpDNXRES3RGYmYwV08y
        M2g3NEtQM2IwTFNSbjVDQm11d0IrUzJRa0VVCjYyUTFJVGFSWDUwQzQ3ODB6UW1N
        WFZHY25uaXBXYTlpNS9RN0xENjB0TVkKLS0tIEVqbHBJSmozT0gzb3cyQjI3bWV5
        aU8zWVJzZWsxSkNHdnoxZThaWFVnaWsKsFQVNuXtT9l2jzx7z0DiHFUXi8Oxi0p1
        OKL1q/FaWuirAaxqJ3NZ0kBG+j7h7zsxa/Ei25mAQtQcXucywfCgxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T15:59:37Z"
  mac: ENC[AES256_GCM,data:IZkkTVLgzTJZahW4uhl04OPTM9qZMTkP7SJsVc7leRy+a85nEaP6ttXeIY5OXVW6wEYQzQAIKR8S+V5ynSTkOX1PA/Px0DdcmAyAV1kQqPGM4mxBGt9db68pLTaS975tgErE24WA8bBBFGg95otCERhRjy56EXWLmUxWGKIyQQA=,iv:emR+c7n2kKpfAghG5tx4qj119eXSNrMOgxN7bTZm3fE=,tag:3CMXbGvQRdHfDV1z4AQqzQ==,type:str]
  encrypted_regex: ^(data|stringData|apiKey|rootPassword|secretKey|adminPassword|basicAuthPassword|password|secret_key|secret|WOODPECKER_FORGEJO_SECRET|token)$
  mac_only_encrypted: true
  version: 3.11.0
